name: 'PR Tests'
on:
  pull_request:
    branches: [main, develop, staging]

jobs:
  pr-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --ignore-scripts

      - name: Run lint and type checks
        run: yarn lint

      # - name: Run tests
      #   run: yarn test
